[package]
name = "system"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-core.workspace = true
sapic-errors.workspace = true
sapic-base.workspace = true

moss_applib.workspace = true   # TODO: Remove this once we move errors to base crate
moss_fs.workspace = true       # TODO: Remove this once we move FS operations from workspace_service
moss_storage2.workspace = true
moss_text.workspace = true
moss_keyring.workspace = true  # TODO: move impl to platform crate
moss_git.workspace = true
moss_edit.workspace = true

joinerror.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
rustc-hash.workspace = true
tokio = { workspace = true }
async-trait.workspace = true
inventory.workspace = true
tracing.workspace = true
chrono.workspace = true

[features]
integration-tests = []
