[package]
name = "moss_edit"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
json-patch = { workspace = true }
jsonptr = { workspace = true }
joinerror = { workspace = true }
serde_json = { workspace = true }

[features]
integration-tests = []
