[package]
name = "window2"
version = "0.1.0"
edition = "2024"

[dependencies]
moss_applib = { workspace = true }

async-trait = { workspace = true }
tauri = { workspace = true }
derive_more = { workspace = true, features = ["deref"] }

[features]
external = []
integration-tests = []
