[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-system.workspace = true

moss_app_delegate.workspace = true
moss_applib.workspace = true

async-trait.workspace = true
derive_more.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
inventory.workspace = true

[features]
integration-tests = []
