[package]
name = "runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-system.workspace = true
sapic-platform.workspace = true
sapic-base.workspace = true
sapic-errors.workspace = true
sapic-core.workspace = true

moss_applib.workspace = true
moss_fs.workspace = true
moss_app_delegate.workspace = true

async-trait.workspace = true
derive_more.workspace = true
tokio.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
inventory.workspace = true
joinerror.workspace = true
tracing.workspace = true
rustc-hash.workspace = true
tauri.workspace = true

[features]
integration-tests = []
