[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-errors.workspace = true
sapic-core.workspace = true
sapic-system.workspace = true
sapic-base = { workspace = true }

moss_fs = { workspace = true }
moss_edit = { workspace = true }
moss_text = { workspace = true }
moss_applib = { workspace = true }
moss_git = { workspace = true }
moss_common = { workspace = true }
moss_environment = { workspace = true }
moss_storage2 = { workspace = true }

ts-rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
joinerror = { workspace = true }
derive_more = { workspace = true, features = ["deref", "display"] }
regorus = { workspace = true }
tokio = { workspace = true }
json-patch = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
async-trait = { workspace = true }
tracing = { workspace = true }
oauth2 = { workspace = true }
chrono = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
webbrowser = { workspace = true }
jsonptr = { workspace = true }

# Making SSH work on Windows
[target.'cfg(windows)'.dependencies]
libssh2-sys = { version = "0.3.1", features = ["openssl-on-win32", "vendored-openssl"] }

[features]
integration-tests = []
