[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-core.workspace = true
sapic-system.workspace = true
sapic-base = { workspace = true }

moss_fs = { workspace = true }
moss_edit = { workspace = true }
moss_text = { workspace = true }
moss_applib = { workspace = true }

ts-rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
joinerror = { workspace = true }
derive_more = { workspace = true, features = ["deref", "display"] }
regorus = { workspace = true }
tokio = { workspace = true }
json-patch = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
async-trait = { workspace = true }
tracing = { workspace = true }

[features]
integration-tests = []
