[package]
name = "platform"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-base = { workspace = true }
moss_fs = { workspace = true }

ts-rs = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
joinerror = { workspace = true }
derive_more = { workspace = true, features = ["deref", "display"] }
regorus = { workspace = true }

[features]
integration-tests = []
