[package]
name = "moss_storage"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
sapic-core.workspace = true

moss_db.workspace = true
moss_applib.workspace = true
joinerror.workspace = true

anyhow.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
smallvec.workspace = true
redb.workspace = true
tokio.workspace = true
async-trait.workspace = true
hcl-rs.workspace = true

[features]
integration-tests = []
