[package]
name = "moss_user"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
sapic-core.workspace = true

moss_server_api.workspace = true
moss_applib.workspace = true
moss_keyring.workspace = true
moss_id_macro = { workspace = true }

oauth2 = { workspace = true, features = ["ureq"] }
reqwest = { workspace = true, features = ["json"] }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ts-rs = { workspace = true, features = ["chrono-impl"] }
nanoid = { workspace = true }
joinerror = { workspace = true }
chrono = { workspace = true }

[features]
integration-tests = []
