[package]
name = "moss_text"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
arcstr = { workspace = true, features = ["serde"] }
bstr.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
moss_testutils.workspace = true

[features]
integration-tests = []
