[package]
name = "moss_vault"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
moss_db.workspace = true

serde = { workspace = true, features = ["derive"] }

[features]
integration-tests = []
