[package]
name = "moss-wasm"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http.workspace = true
sha2.workspace = true

# HCL experiment
hcl-rs.workspace = true

[features]
integration-tests = []
