[package]
name = "moss_language"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
sapic-runtime.workspace = true

moss_app_delegate.workspace = true
moss_applib.workspace = true
moss_fs.workspace = true
joinerror.workspace = true

serde.workspace = true
serde_json.workspace = true
ts-rs.workspace = true
derive_more = { workspace = true, features = ["display", "deref"] }
async-trait.workspace = true
tokio.workspace = true
inventory.workspace = true
rustc-hash.workspace = true

[features]
integration-tests = []
