[package]
name = "window"
version = "0.1.0"
edition = "2024"
license = "MIT"

[build-dependencies]
serde_json.workspace = true

[dependencies]
sapic-runtime.workspace = true
sapic-platform.workspace = true
sapic-base.workspace = true
sapic-system.workspace = true

moss_app_delegate.workspace = true
moss_server_api.workspace = true
moss_user.workspace = true
moss_common.workspace = true
moss_fs.workspace = true
moss_applib.workspace = true
moss_text.workspace = true
moss_workspace.workspace = true
moss_activity_broadcaster.workspace = true
moss_environment.workspace = true
moss_git_hosting_provider.workspace = true
moss_keyring.workspace = true
moss_logging.workspace = true
moss_id_macro.workspace = true
moss_bindingutils.workspace = true
moss_edit.workspace = true
moss_extension_points.workspace = true
moss_language.workspace = true
moss_storage2.workspace = true

static_json.workspace = true
inventory.workspace = true
json-patch.workspace = true
joinerror.workspace = true
tauri = { workspace = true, features = ["wry"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["time", "rt-multi-thread"] }
rustc-hash.workspace = true
serde_json.workspace = true
serde = { workspace = true, features = ["derive", "rc"] }
ts-rs.workspace = true
chrono.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "json", "chrono", "ansi", "env-filter"] }
tracing-appender.workspace = true
derive_more = { workspace = true, features = ["deref", "deref_mut", "from"] }
validator.workspace = true
async-trait.workspace = true
nanoid.workspace = true
regorus = { workspace = true, features = ["regex"] }
indexmap.workspace = true

[dev-dependencies]
futures.workspace = true
reqwest = { workspace = true, features = ["json"] }
tauri = { workspace = true, features = ["test"] }
moss_testutils.workspace = true
moss_applib = { workspace = true, features = ["test"] }

[features]
integration-tests = ["moss_keyring/test", "moss_app_delegate/integration-tests", "moss_git_hosting_provider/test"]
