[package]
name = "moss_storage2"
version = "0.1.0"
edition = "2024"

[dependencies]
sapic-core.workspace = true

moss_applib.workspace = true
moss_logging.workspace = true
moss_app_delegate.workspace = true
moss_common.workspace = true

joinerror = { workspace = true, features = ["sqlx-sqlite", "sqlx-migrate"] }
sqlx = { workspace = true, features = ["sqlite"] }
rustc-hash = { workspace = true }
derive_more = { workspace = true, features = ["deref"] }
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde_json.workspace = true

[features]
integration-tests = []
