[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
joinerror.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "time"] }

[features]
integration-tests = []
