[package]
name = "moss_server_api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
sapic-core.workspace = true
moss_applib.workspace = true
moss_app_delegate.workspace = true

async-trait.workspace = true
joinerror.workspace = true
reqwest = { workspace = true, features = ["json"] }
serde.workspace = true

[features]
integration-tests = []
