name: Software Bill of Materials
on:
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
        with:
          fetch-depth: "0"

      - name: Set Up Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: "package.json"

      - name: Install cdxgen (SBOM generator)
        run: |
          npm install -g @cyclonedx/cdxgen@11.11.0

      - name: Generate SBOM
        run: |
          cdxgen -r -o bom.json

      - name: Run vulnerability scanning with trivy
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: "sbom"
          scan-ref: bom.json
          format: table
          output: trivy-sbom-report.txt
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: sbom
          path: bom.json

      - name: Upload Trivy SBOM report as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: trivy-sbom-report
          path: trivy-sbom-report.txt

